export const DB_NAME_CSAPlans = "csa_plans"
export const DB_NAME_Stocks = "stocks"
export const DB_NAME_Customer = "customers"
export const DB_NAME_Farmer = "farmers"
export const DB_NAME_Order = "orders"
export const DB_NAME_Deliverypartner = "deliverypartners"
export const DB_NAME_Cart = "cart"